export interface FundData {
  id: string;
  name: string;
  returnPercentage: number;
  aum?: string;
  expenseRatio?: number;
  category?: string;
  fundType: 'ETF' | 'Index Fund';
  assetType: 'Equity' | 'Debt';
  listedAt: 'NSE' | 'BSE' | 'Both';
}

export interface FundDetailData {
  id: string;
  name: string;
  fundType: 'ETF' | 'Index Fund';
  riskLevel: 'Very High Risk' | 'High Risk' | 'Moderate Risk' | 'Low Risk';
  fundCategory: 'Open Ended' | 'Close Ended';
  description: string;
  benchmark: string;
  fundManagers: string[];
  launchDate: string;
  aum: string;
  nav: string;
  navDate: string;
  expenseRatio: number;
  returnPercentage: number;
  category?: string;
  assetType: 'Equity' | 'Debt';
  listedAt: 'NSE' | 'BSE' | 'Both';
  performanceData: Array<{
    date: string;
    value: number;
  }>;
  logo?: string;
}

export const fundDetails: Record<string, FundDetailData> = {
  // Existing funds (1-8)
  '1': {
    id: '1',
    name: 'Bandhan Nifty 50',
    fundType: 'ETF',
    riskLevel: 'Very High Risk',
    fundCategory: 'Open Ended',
    description: 'The principal investment objective of the scheme is to invest in stocks of companies comprising Nifty 50 Index and endeavor to achieve return equivalent to Nifty 50 Index by passive investment.',
    benchmark: 'Nifty 50 TRI',
    fundManagers: ['Rahul Jain', 'Priya Sharma'],
    launchDate: '15 Jan, 2021',
    aum: '₹ 12,450.75 Cr.',
    nav: '₹ 156.78',
    navDate: '30 Jun, 2025',
    expenseRatio: 0.08,
    returnPercentage: 11.55,
    category: 'Large Cap Equity',
    assetType: 'Equity',
    listedAt: 'NSE',
    performanceData: [
      { date: 'Feb 25', value: 14000 },
      { date: 'Mar 25', value: 15200 },
      { date: 'Apr 25', value: 16500 },
      { date: 'May 25', value: 17800 },
      { date: 'Jun 25', value: 19000 },
    ]
  },
  '2': {
    id: '2',
    name: 'Motilal Oswal Nifty 500',
    fundType: 'Index Fund',
    riskLevel: 'Very High Risk',
    fundCategory: 'Open Ended',
    description: 'The scheme aims to provide returns that closely correspond to the total returns of the securities as represented by the underlying index, subject to tracking error.',
    benchmark: 'Nifty 500 TRI',
    fundManagers: ['Suresh Kumar', 'Anita Patel'],
    launchDate: '22 Mar, 2019',
    aum: '₹ 8,920.30 Cr.',
    nav: '₹ 234.56',
    navDate: '30 Jun, 2025',
    expenseRatio: 0.10,
    returnPercentage: 12.55,
    category: 'Index Fund',
    assetType: 'Equity',
    listedAt: 'BSE',
    performanceData: [
      { date: 'Feb 25', value: 21000 },
      { date: 'Mar 25', value: 22500 },
      { date: 'Apr 25', value: 24000 },
      { date: 'May 25', value: 25500 },
      { date: 'Jun 25', value: 27000 },
    ]
  },
  '3': {
    id: '3',
    name: 'UTI Nifty 50 Index',
    fundType: 'Index Fund',
    riskLevel: 'Very High Risk',
    fundCategory: 'Open Ended',
    description: 'The principal investment objective of the scheme is to invest in stocks of companies comprising Nifty 50 Index and endeavor to achieve return equivalent to Nifty 50 Index by passive investment.',
    benchmark: 'Nifty 50 TRI',
    fundManagers: ['Ayush Jain', 'Sharwan Kumar Goyal'],
    launchDate: '06 Mar, 2000',
    aum: '₹ 24,115.50 Cr.',
    nav: '₹ 245.67',
    navDate: '30 Jun, 2025',
    expenseRatio: 0.10,
    returnPercentage: 11.55,
    category: 'Index Fund',
    assetType: 'Equity',
    listedAt: 'Both',
    performanceData: [
      { date: 'Feb 25', value: 18000 },
      { date: 'Mar 25', value: 19500 },
      { date: 'Apr 25', value: 21000 },
      { date: 'May 25', value: 22500 },
      { date: 'Jun 25', value: 24000 },
    ]
  },
  '4': {
    id: '4',
    name: 'ICICI Prudential Nifty 50',
    fundType: 'ETF',
    riskLevel: 'Very High Risk',
    fundCategory: 'Open Ended',
    description: 'The scheme seeks to provide returns that closely correspond to the total returns of the securities as represented by the underlying index.',
    benchmark: 'Nifty 50 TRI',
    fundManagers: ['Rajesh Mehta', 'Kavita Singh'],
    launchDate: '12 Sep, 2015',
    aum: '₹ 18,750.25 Cr.',
    nav: '₹ 189.45',
    navDate: '30 Jun, 2025',
    expenseRatio: 0.09,
    returnPercentage: 11.55,
    category: 'Equity Fund',
    assetType: 'Equity',
    listedAt: 'NSE',
    performanceData: [
      { date: 'Feb 25', value: 17000 },
      { date: 'Mar 25', value: 18200 },
      { date: 'Apr 25', value: 19500 },
      { date: 'May 25', value: 20800 },
      { date: 'Jun 25', value: 22000 },
    ]
  },
  '5': {
    id: '5',
    name: 'HDFC BSE Sensex',
    fundType: 'Index Fund',
    riskLevel: 'Very High Risk',
    fundCategory: 'Open Ended',
    description: 'The scheme aims to provide returns that closely correspond to the total returns of the securities as represented by the BSE Sensex.',
    benchmark: 'BSE Sensex TRI',
    fundManagers: ['Krishna Kumar'],
    launchDate: '08 Jul, 2002',
    aum: '₹ 15,680.90 Cr.',
    nav: '₹ 312.34',
    navDate: '30 Jun, 2025',
    expenseRatio: 0.12,
    returnPercentage: 11.55,
    category: 'Index Fund',
    assetType: 'Equity',
    listedAt: 'BSE',
    performanceData: [
      { date: 'Feb 25', value: 28000 },
      { date: 'Mar 25', value: 29500 },
      { date: 'Apr 25', value: 31000 },
      { date: 'May 25', value: 32500 },
      { date: 'Jun 25', value: 34000 },
    ]
  },
  '6': {
    id: '6',
    name: 'TATA BSE Sensex',
    fundType: 'Index Fund',
    riskLevel: 'Very High Risk',
    fundCategory: 'Open Ended',
    description: 'The scheme seeks to provide returns that closely correspond to the total returns of the securities as represented by the BSE Sensex.',
    benchmark: 'BSE Sensex TRI',
    fundManagers: ['Vikram Patel', 'Sunita Rao'],
    launchDate: '14 Nov, 2018',
    aum: '₹ 6,450.20 Cr.',
    nav: '₹ 178.90',
    navDate: '30 Jun, 2025',
    expenseRatio: 0.11,
    returnPercentage: 11.55,
    category: 'Index Fund',
    assetType: 'Equity',
    listedAt: 'BSE',
    performanceData: [
      { date: 'Feb 25', value: 16000 },
      { date: 'Mar 25', value: 17200 },
      { date: 'Apr 25', value: 18500 },
      { date: 'May 25', value: 19800 },
      { date: 'Jun 25', value: 21000 },
    ]
  },
  '7': {
    id: '7',
    name: 'SBI Nifty 50 ETF',
    fundType: 'ETF',
    riskLevel: 'Very High Risk',
    fundCategory: 'Open Ended',
    description: 'The scheme aims to provide returns that closely correspond to the total returns of the securities as represented by the Nifty 50 Index.',
    benchmark: 'Nifty 50 TRI',
    fundManagers: ['Amit Kumar', 'Priya Verma'],
    launchDate: '25 May, 2017',
    aum: '₹ 22,890.45 Cr.',
    nav: '₹ 267.89',
    navDate: '30 Jun, 2025',
    expenseRatio: 0.07,
    returnPercentage: 11.55,
    category: 'Index Fund',
    assetType: 'Equity',
    listedAt: 'NSE',
    performanceData: [
      { date: 'Feb 25', value: 24000 },
      { date: 'Mar 25', value: 25500 },
      { date: 'Apr 25', value: 27000 },
      { date: 'May 25', value: 28500 },
      { date: 'Jun 25', value: 30000 },
    ]
  },
  '8': {
    id: '8',
    name: 'Axis Nifty 50',
    fundType: 'Index Fund',
    riskLevel: 'Moderate Risk',
    fundCategory: 'Open Ended',
    description: 'The scheme aims to provide returns that closely correspond to the total returns of the securities as represented by the Nifty 50 Index.',
    benchmark: 'Nifty 50 TRI',
    fundManagers: ['Rahul Sharma', 'Meera Iyer'],
    launchDate: '03 Dec, 2016',
    aum: '₹ 9,120.75 Cr.',
    nav: '₹ 145.67',
    navDate: '30 Jun, 2025',
    expenseRatio: 0.10,
    returnPercentage: -1.55,
    category: 'Index Fund',
    assetType: 'Debt',
    listedAt: 'NSE',
    performanceData: [
      { date: 'Feb 25', value: 15000 },
      { date: 'Mar 25', value: 14800 },
      { date: 'Apr 25', value: 14600 },
      { date: 'May 25', value: 14400 },
      { date: 'Jun 25', value: 14200 },
    ]
  },

  // New Nifty 50 Funds
  '9': {
    id: '9',
    name: 'Kotak Nifty 50 ETF',
    fundType: 'ETF',
    riskLevel: 'Very High Risk',
    fundCategory: 'Open Ended',
    description: 'The scheme aims to provide returns that closely correspond to the total returns of the securities as represented by the Nifty 50 Index.',
    benchmark: 'Nifty 50 TRI',
    fundManagers: ['Harshad Borawake', 'Abhishek Bisen'],
    launchDate: '10 Apr, 2015',
    aum: '₹ 16,750.30 Cr.',
    nav: '₹ 198.45',
    navDate: '30 Jun, 2025',
    expenseRatio: 0.08,
    returnPercentage: 13.25,
    category: 'Large Cap Equity',
    assetType: 'Equity',
    listedAt: 'NSE',
    performanceData: [
      { date: 'Feb 25', value: 18500 },
      { date: 'Mar 25', value: 19800 },
      { date: 'Apr 25', value: 21200 },
      { date: 'May 25', value: 22600 },
      { date: 'Jun 25', value: 24000 },
    ]
  },
  '10': {
    id: '10',
    name: 'Nippon India Nifty 50',
    fundType: 'Index Fund',
    riskLevel: 'Very High Risk',
    fundCategory: 'Open Ended',
    description: 'The scheme aims to provide returns that closely correspond to the total returns of the securities as represented by the Nifty 50 Index.',
    benchmark: 'Nifty 50 TRI',
    fundManagers: ['Sailesh Raj Bhan', 'Meenakshi Dawar'],
    launchDate: '28 Sep, 2009',
    aum: '₹ 11,230.45 Cr.',
    nav: '₹ 167.89',
    navDate: '30 Jun, 2025',
    expenseRatio: 0.11,
    returnPercentage: 12.85,
    category: 'Index Fund',
    assetType: 'Equity',
    listedAt: 'Both',
    performanceData: [
      { date: 'Feb 25', value: 16500 },
      { date: 'Mar 25', value: 17800 },
      { date: 'Apr 25', value: 19200 },
      { date: 'May 25', value: 20600 },
      { date: 'Jun 25', value: 22000 },
    ]
  },

  // Sensex Funds
  '11': {
    id: '11',
    name: 'Kotak BSE Sensex',
    fundType: 'Index Fund',
    riskLevel: 'Very High Risk',
    fundCategory: 'Open Ended',
    description: 'The scheme aims to provide returns that closely correspond to the total returns of the securities as represented by the BSE Sensex.',
    benchmark: 'BSE Sensex TRI',
    fundManagers: ['Harshad Borawake', 'Abhishek Bisen'],
    launchDate: '25 Jun, 2011',
    aum: '₹ 8,450.75 Cr.',
    nav: '₹ 234.56',
    navDate: '30 Jun, 2025',
    expenseRatio: 0.12,
    returnPercentage: 14.25,
    category: 'Index Fund',
    assetType: 'Equity',
    listedAt: 'BSE',
    performanceData: [
      { date: 'Feb 25', value: 22000 },
      { date: 'Mar 25', value: 23500 },
      { date: 'Apr 25', value: 25000 },
      { date: 'May 25', value: 26500 },
      { date: 'Jun 25', value: 28000 },
    ]
  },
  '12': {
    id: '12',
    name: 'SBI BSE Sensex ETF',
    fundType: 'ETF',
    riskLevel: 'Very High Risk',
    fundCategory: 'Open Ended',
    description: 'The scheme aims to provide returns that closely correspond to the total returns of the securities as represented by the BSE Sensex.',
    benchmark: 'BSE Sensex TRI',
    fundManagers: ['Amit Kumar', 'Priya Verma'],
    launchDate: '15 Mar, 2016',
    aum: '₹ 12,890.30 Cr.',
    nav: '₹ 289.67',
    navDate: '30 Jun, 2025',
    expenseRatio: 0.09,
    returnPercentage: 13.75,
    category: 'Index Fund',
    assetType: 'Equity',
    listedAt: 'BSE',
    performanceData: [
      { date: 'Feb 25', value: 25000 },
      { date: 'Mar 25', value: 26500 },
      { date: 'Apr 25', value: 28000 },
      { date: 'May 25', value: 29500 },
      { date: 'Jun 25', value: 31000 },
    ]
  },

  // Mid Cap Funds
  '13': {
    id: '13',
    name: 'Motilal Oswal Nifty Midcap 150',
    fundType: 'Index Fund',
    riskLevel: 'Very High Risk',
    fundCategory: 'Open Ended',
    description: 'The scheme aims to provide returns that closely correspond to the total returns of the securities as represented by the Nifty Midcap 150 Index.',
    benchmark: 'Nifty Midcap 150 TRI',
    fundManagers: ['Suresh Kumar', 'Anita Patel'],
    launchDate: '18 Jan, 2020',
    aum: '₹ 5,230.45 Cr.',
    nav: '₹ 145.78',
    navDate: '30 Jun, 2025',
    expenseRatio: 0.15,
    returnPercentage: 18.45,
    category: 'Mid Cap Equity',
    assetType: 'Equity',
    listedAt: 'NSE',
    performanceData: [
      { date: 'Feb 25', value: 12000 },
      { date: 'Mar 25', value: 13500 },
      { date: 'Apr 25', value: 15000 },
      { date: 'May 25', value: 16500 },
      { date: 'Jun 25', value: 18000 },
    ]
  },
  '14': {
    id: '14',
    name: 'HDFC Nifty Midcap 150',
    fundType: 'Index Fund',
    riskLevel: 'Very High Risk',
    fundCategory: 'Open Ended',
    description: 'The scheme aims to provide returns that closely correspond to the total returns of the securities as represented by the Nifty Midcap 150 Index.',
    benchmark: 'Nifty Midcap 150 TRI',
    fundManagers: ['Krishna Kumar'],
    launchDate: '22 Feb, 2021',
    aum: '₹ 3,890.75 Cr.',
    nav: '₹ 123.45',
    navDate: '30 Jun, 2025',
    expenseRatio: 0.14,
    returnPercentage: 16.85,
    category: 'Mid Cap Equity',
    assetType: 'Equity',
    listedAt: 'NSE',
    performanceData: [
      { date: 'Feb 25', value: 10000 },
      { date: 'Mar 25', value: 11200 },
      { date: 'Apr 25', value: 12500 },
      { date: 'May 25', value: 13800 },
      { date: 'Jun 25', value: 15000 },
    ]
  },

  // Small Cap Funds
  '15': {
    id: '15',
    name: 'Axis Nifty Smallcap 250',
    fundType: 'Index Fund',
    riskLevel: 'Very High Risk',
    fundCategory: 'Open Ended',
    description: 'The scheme aims to provide returns that closely correspond to the total returns of the securities as represented by the Nifty Smallcap 250 Index.',
    benchmark: 'Nifty Smallcap 250 TRI',
    fundManagers: ['Rahul Sharma', 'Meera Iyer'],
    launchDate: '05 Mar, 2022',
    aum: '₹ 2,450.30 Cr.',
    nav: '₹ 89.67',
    navDate: '30 Jun, 2025',
    expenseRatio: 0.18,
    returnPercentage: 22.35,
    category: 'Small Cap Equity',
    assetType: 'Equity',
    listedAt: 'NSE',
    performanceData: [
      { date: 'Feb 25', value: 8000 },
      { date: 'Mar 25', value: 9200 },
      { date: 'Apr 25', value: 10500 },
      { date: 'May 25', value: 11800 },
      { date: 'Jun 25', value: 13000 },
    ]
  },
  '16': {
    id: '16',
    name: 'ICICI Prudential Nifty Smallcap 250',
    fundType: 'Index Fund',
    riskLevel: 'Very High Risk',
    fundCategory: 'Open Ended',
    description: 'The scheme aims to provide returns that closely correspond to the total returns of the securities as represented by the Nifty Smallcap 250 Index.',
    benchmark: 'Nifty Smallcap 250 TRI',
    fundManagers: ['Rajesh Mehta', 'Kavita Singh'],
    launchDate: '12 Apr, 2022',
    aum: '₹ 1,890.45 Cr.',
    nav: '₹ 78.34',
    navDate: '30 Jun, 2025',
    expenseRatio: 0.17,
    returnPercentage: 20.85,
    category: 'Small Cap Equity',
    assetType: 'Equity',
    listedAt: 'NSE',
    performanceData: [
      { date: 'Feb 25', value: 6500 },
      { date: 'Mar 25', value: 7500 },
      { date: 'Apr 25', value: 8500 },
      { date: 'May 25', value: 9500 },
      { date: 'Jun 25', value: 10500 },
    ]
  },

  // Sector Funds - Technology
  '17': {
    id: '17',
    name: 'Nippon India Nifty IT',
    fundType: 'Index Fund',
    riskLevel: 'Very High Risk',
    fundCategory: 'Open Ended',
    description: 'The scheme aims to provide returns that closely correspond to the total returns of the securities as represented by the Nifty IT Index.',
    benchmark: 'Nifty IT TRI',
    fundManagers: ['Sailesh Raj Bhan', 'Meenakshi Dawar'],
    launchDate: '08 Jun, 2020',
    aum: '₹ 3,450.75 Cr.',
    nav: '₹ 156.78',
    navDate: '30 Jun, 2025',
    expenseRatio: 0.16,
    returnPercentage: 25.45,
    category: 'Sector Fund - Technology',
    assetType: 'Equity',
    listedAt: 'NSE',
    performanceData: [
      { date: 'Feb 25', value: 12000 },
      { date: 'Mar 25', value: 13800 },
      { date: 'Apr 25', value: 15600 },
      { date: 'May 25', value: 17400 },
      { date: 'Jun 25', value: 19200 },
    ]
  },
  '18': {
    id: '18',
    name: 'HDFC Nifty IT ETF',
    fundType: 'ETF',
    riskLevel: 'Very High Risk',
    fundCategory: 'Open Ended',
    description: 'The scheme aims to provide returns that closely correspond to the total returns of the securities as represented by the Nifty IT Index.',
    benchmark: 'Nifty IT TRI',
    fundManagers: ['Krishna Kumar'],
    launchDate: '15 Jul, 2021',
    aum: '₹ 2,890.30 Cr.',
    nav: '₹ 145.67',
    navDate: '30 Jun, 2025',
    expenseRatio: 0.15,
    returnPercentage: 24.85,
    category: 'Sector Fund - Technology',
    assetType: 'Equity',
    listedAt: 'NSE',
    performanceData: [
      { date: 'Feb 25', value: 10000 },
      { date: 'Mar 25', value: 11500 },
      { date: 'Apr 25', value: 13000 },
      { date: 'May 25', value: 14500 },
      { date: 'Jun 25', value: 16000 },
    ]
  },

  // Sector Funds - Banking
  '19': {
    id: '19',
    name: 'SBI Nifty Bank ETF',
    fundType: 'ETF',
    riskLevel: 'Very High Risk',
    fundCategory: 'Open Ended',
    description: 'The scheme aims to provide returns that closely correspond to the total returns of the securities as represented by the Nifty Bank Index.',
    benchmark: 'Nifty Bank TRI',
    fundManagers: ['Amit Kumar', 'Priya Verma'],
    launchDate: '22 Aug, 2019',
    aum: '₹ 8,750.45 Cr.',
    nav: '₹ 234.56',
    navDate: '30 Jun, 2025',
    expenseRatio: 0.12,
    returnPercentage: 19.75,
    category: 'Sector Fund - Banking',
    assetType: 'Equity',
    listedAt: 'NSE',
    performanceData: [
      { date: 'Feb 25', value: 18000 },
      { date: 'Mar 25', value: 19800 },
      { date: 'Apr 25', value: 21600 },
      { date: 'May 25', value: 23400 },
      { date: 'Jun 25', value: 25200 },
    ]
  },
  '20': {
    id: '20',
    name: 'Kotak Nifty Bank',
    fundType: 'Index Fund',
    riskLevel: 'Very High Risk',
    fundCategory: 'Open Ended',
    description: 'The scheme aims to provide returns that closely correspond to the total returns of the securities as represented by the Nifty Bank Index.',
    benchmark: 'Nifty Bank TRI',
    fundManagers: ['Harshad Borawake', 'Abhishek Bisen'],
    launchDate: '10 Sep, 2020',
    aum: '₹ 6,230.75 Cr.',
    nav: '₹ 198.45',
    navDate: '30 Jun, 2025',
    expenseRatio: 0.13,
    returnPercentage: 18.95,
    category: 'Sector Fund - Banking',
    assetType: 'Equity',
    listedAt: 'NSE',
    performanceData: [
      { date: 'Feb 25', value: 15000 },
      { date: 'Mar 25', value: 16500 },
      { date: 'Apr 25', value: 18000 },
      { date: 'May 25', value: 19500 },
      { date: 'Jun 25', value: 21000 },
    ]
  },

  // International Funds
  '21': {
    id: '21',
    name: 'Motilal Oswal NASDAQ 100',
    fundType: 'Index Fund',
    riskLevel: 'Very High Risk',
    fundCategory: 'Open Ended',
    description: 'The scheme aims to provide returns that closely correspond to the total returns of the securities as represented by the NASDAQ 100 Index.',
    benchmark: 'NASDAQ 100 TRI',
    fundManagers: ['Suresh Kumar', 'Anita Patel'],
    launchDate: '15 Jan, 2021',
    aum: '₹ 4,890.30 Cr.',
    nav: '₹ 167.89',
    navDate: '30 Jun, 2025',
    expenseRatio: 0.20,
    returnPercentage: 28.45,
    category: 'International Fund',
    assetType: 'Equity',
    listedAt: 'NSE',
    performanceData: [
      { date: 'Feb 25', value: 14000 },
      { date: 'Mar 25', value: 15800 },
      { date: 'Apr 25', value: 17600 },
      { date: 'May 25', value: 19400 },
      { date: 'Jun 25', value: 21200 },
    ]
  },
  '22': {
    id: '22',
    name: 'ICICI Prudential US Bluechip',
    fundType: 'Index Fund',
    riskLevel: 'Very High Risk',
    fundCategory: 'Open Ended',
    description: 'The scheme aims to provide returns that closely correspond to the total returns of the securities as represented by the S&P 500 Index.',
    benchmark: 'S&P 500 TRI',
    fundManagers: ['Rajesh Mehta', 'Kavita Singh'],
    launchDate: '08 Mar, 2022',
    aum: '₹ 3,450.75 Cr.',
    nav: '₹ 145.67',
    navDate: '30 Jun, 2025',
    expenseRatio: 0.22,
    returnPercentage: 26.85,
    category: 'International Fund',
    assetType: 'Equity',
    listedAt: 'NSE',
    performanceData: [
      { date: 'Feb 25', value: 12000 },
      { date: 'Mar 25', value: 13500 },
      { date: 'Apr 25', value: 15000 },
      { date: 'May 25', value: 16500 },
      { date: 'Jun 25', value: 18000 },
    ]
  },

  // Debt Funds
  '23': {
    id: '23',
    name: 'HDFC Nifty 50 Equal Weight',
    fundType: 'Index Fund',
    riskLevel: 'Moderate Risk',
    fundCategory: 'Open Ended',
    description: 'The scheme aims to provide returns that closely correspond to the total returns of the securities as represented by the Nifty 50 Equal Weight Index.',
    benchmark: 'Nifty 50 Equal Weight TRI',
    fundManagers: ['Krishna Kumar'],
    launchDate: '12 Apr, 2021',
    aum: '₹ 2,890.45 Cr.',
    nav: '₹ 123.45',
    navDate: '30 Jun, 2025',
    expenseRatio: 0.14,
    returnPercentage: 15.75,
    category: 'Index Fund',
    assetType: 'Debt',
    listedAt: 'NSE',
    performanceData: [
      { date: 'Feb 25', value: 10000 },
      { date: 'Mar 25', value: 10800 },
      { date: 'Apr 25', value: 11600 },
      { date: 'May 25', value: 12400 },
      { date: 'Jun 25', value: 13200 },
    ]
  },
  '24': {
    id: '24',
    name: 'Axis Nifty 100 Equal Weight',
    fundType: 'Index Fund',
    riskLevel: 'Moderate Risk',
    fundCategory: 'Open Ended',
    description: 'The scheme aims to provide returns that closely correspond to the total returns of the securities as represented by the Nifty 100 Equal Weight Index.',
    benchmark: 'Nifty 100 Equal Weight TRI',
    fundManagers: ['Rahul Sharma', 'Meera Iyer'],
    launchDate: '25 May, 2022',
    aum: '₹ 1,890.30 Cr.',
    nav: '₹ 98.67',
    navDate: '30 Jun, 2025',
    expenseRatio: 0.16,
    returnPercentage: 14.25,
    category: 'Index Fund',
    assetType: 'Debt',
    listedAt: 'NSE',
    performanceData: [
      { date: 'Feb 25', value: 8000 },
      { date: 'Mar 25', value: 8600 },
      { date: 'Apr 25', value: 9200 },
      { date: 'May 25', value: 9800 },
      { date: 'Jun 25', value: 10400 },
    ]
  },

  // ESG Funds
  '25': {
    id: '25',
    name: 'SBI ESG Fund',
    fundType: 'Index Fund',
    riskLevel: 'High Risk',
    fundCategory: 'Open Ended',
    description: 'The scheme aims to provide returns that closely correspond to the total returns of the securities as represented by the Nifty 100 ESG Index.',
    benchmark: 'Nifty 100 ESG TRI',
    fundManagers: ['Amit Kumar', 'Priya Verma'],
    launchDate: '18 Jun, 2022',
    aum: '₹ 3,450.75 Cr.',
    nav: '₹ 156.78',
    navDate: '30 Jun, 2025',
    expenseRatio: 0.18,
    returnPercentage: 17.85,
    category: 'ESG Fund',
    assetType: 'Equity',
    listedAt: 'NSE',
    performanceData: [
      { date: 'Feb 25', value: 12000 },
      { date: 'Mar 25', value: 12800 },
      { date: 'Apr 25', value: 13600 },
      { date: 'May 25', value: 14400 },
      { date: 'Jun 25', value: 15200 },
    ]
  },
  '26': {
    id: '26',
    name: 'ICICI Prudential ESG Fund',
    fundType: 'ETF',
    riskLevel: 'High Risk',
    fundCategory: 'Open Ended',
    description: 'The scheme aims to provide returns that closely correspond to the total returns of the securities as represented by the Nifty 100 ESG Index.',
    benchmark: 'Nifty 100 ESG TRI',
    fundManagers: ['Rajesh Mehta', 'Kavita Singh'],
    launchDate: '22 Jul, 2022',
    aum: '₹ 2,890.45 Cr.',
    nav: '₹ 145.67',
    navDate: '30 Jun, 2025',
    expenseRatio: 0.17,
    returnPercentage: 16.95,
    category: 'ESG Fund',
    assetType: 'Equity',
    listedAt: 'NSE',
    performanceData: [
      { date: 'Feb 25', value: 10000 },
      { date: 'Mar 25', value: 10600 },
      { date: 'Apr 25', value: 11200 },
      { date: 'May 25', value: 11800 },
      { date: 'Jun 25', value: 12400 },
    ]
  },

  // Gold Funds
  '27': {
    id: '27',
    name: 'HDFC Gold ETF',
    fundType: 'ETF',
    riskLevel: 'Moderate Risk',
    fundCategory: 'Open Ended',
    description: 'The scheme aims to provide returns that closely correspond to the total returns of the securities as represented by the Gold prices.',
    benchmark: 'Gold Price',
    fundManagers: ['Krishna Kumar'],
    launchDate: '10 Aug, 2021',
    aum: '₹ 5,890.30 Cr.',
    nav: '₹ 234.56',
    navDate: '30 Jun, 2025',
    expenseRatio: 0.25,
    returnPercentage: 8.75,
    category: 'Commodity Fund',
    assetType: 'Debt',
    listedAt: 'NSE',
    performanceData: [
      { date: 'Feb 25', value: 18000 },
      { date: 'Mar 25', value: 18500 },
      { date: 'Apr 25', value: 19000 },
      { date: 'May 25', value: 19500 },
      { date: 'Jun 25', value: 20000 },
    ]
  },
  '28': {
    id: '28',
    name: 'SBI Gold ETF',
    fundType: 'ETF',
    riskLevel: 'Moderate Risk',
    fundCategory: 'Open Ended',
    description: 'The scheme aims to provide returns that closely correspond to the total returns of the securities as represented by the Gold prices.',
    benchmark: 'Gold Price',
    fundManagers: ['Amit Kumar', 'Priya Verma'],
    launchDate: '15 Sep, 2021',
    aum: '₹ 4,450.75 Cr.',
    nav: '₹ 198.45',
    navDate: '30 Jun, 2025',
    expenseRatio: 0.24,
    returnPercentage: 8.25,
    category: 'Commodity Fund',
    assetType: 'Debt',
    listedAt: 'NSE',
    performanceData: [
      { date: 'Feb 25', value: 15000 },
      { date: 'Mar 25', value: 15400 },
      { date: 'Apr 25', value: 15800 },
      { date: 'May 25', value: 16200 },
      { date: 'Jun 25', value: 16600 },
    ]
  },

  // Multi Cap Funds
  '29': {
    id: '29',
    name: 'Motilal Oswal Nifty 500 Equal Weight',
    fundType: 'Index Fund',
    riskLevel: 'Very High Risk',
    fundCategory: 'Open Ended',
    description: 'The scheme aims to provide returns that closely correspond to the total returns of the securities as represented by the Nifty 500 Equal Weight Index.',
    benchmark: 'Nifty 500 Equal Weight TRI',
    fundManagers: ['Suresh Kumar', 'Anita Patel'],
    launchDate: '20 Oct, 2022',
    aum: '₹ 2,890.45 Cr.',
    nav: '₹ 123.45',
    navDate: '30 Jun, 2025',
    expenseRatio: 0.19,
    returnPercentage: 21.85,
    category: 'Multi Cap Equity',
    assetType: 'Equity',
    listedAt: 'NSE',
    performanceData: [
      { date: 'Feb 25', value: 10000 },
      { date: 'Mar 25', value: 11200 },
      { date: 'Apr 25', value: 12400 },
      { date: 'May 25', value: 13600 },
      { date: 'Jun 25', value: 14800 },
    ]
  },
  '30': {
    id: '30',
    name: 'Axis Nifty 500 Equal Weight',
    fundType: 'Index Fund',
    riskLevel: 'Very High Risk',
    fundCategory: 'Open Ended',
    description: 'The scheme aims to provide returns that closely correspond to the total returns of the securities as represented by the Nifty 500 Equal Weight Index.',
    benchmark: 'Nifty 500 Equal Weight TRI',
    fundManagers: ['Rahul Sharma', 'Meera Iyer'],
    launchDate: '05 Nov, 2022',
    aum: '₹ 1,890.30 Cr.',
    nav: '₹ 98.67',
    navDate: '30 Jun, 2025',
    expenseRatio: 0.20,
    returnPercentage: 20.45,
    category: 'Multi Cap Equity',
    assetType: 'Equity',
    listedAt: 'NSE',
    performanceData: [
      { date: 'Feb 25', value: 8000 },
      { date: 'Mar 25', value: 8900 },
      { date: 'Apr 25', value: 9800 },
      { date: 'May 25', value: 10700 },
      { date: 'Jun 25', value: 11600 },
    ]
  }
};

export const getFundDetail = (fundId: string): FundDetailData | null => {
  return fundDetails[fundId] || null;
};

export const getAllFunds = (): FundData[] => {
  return Object.values(fundDetails).map(fund => ({
    id: fund.id,
    name: fund.name,
    returnPercentage: fund.returnPercentage,
    aum: fund.aum,
    expenseRatio: fund.expenseRatio,
    category: fund.category,
    fundType: fund.fundType,
    assetType: fund.assetType,
    listedAt: fund.listedAt
  }));
}; 